version: '3.4'
services:
  netbox: &netbox
    image: vaporio/netbox:develop
    depends_on:
    - postgres
    - redis
    - redis-cache
    - netbox-worker
    env_file: docker/env/netbox.env
    user: '101'
    volumes:
    - ./docker/startup_scripts:/opt/netbox/startup_scripts:z,ro
    - ./docker/initializers:/opt/netbox/initializers:z,ro
    - ./docker/configuration:/etc/netbox/config:z,ro
    - ./reports:/etc/netbox/reports:z,ro
    - ./scripts:/etc/netbox/scripts:z,ro
    - netbox-media-files:/opt/netbox/netbox/media:z
    ports:
    - "8000:8080"
  netbox-worker:
    <<: *netbox
    depends_on:
    - redis
    entrypoint:
    - /opt/netbox/venv/bin/python
    - /opt/netbox/netbox/manage.py
    command:
    - rqworker
    ports: [ ]

  postgres:
    image: postgres:12-alpine
    env_file: docker/env/postgres.env
    ports:
    - "5432:5432"
    volumes:
    - netbox-postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    command:
    - sh
    - -c # this is to evaluate the $REDIS_PASSWORD from the env
    - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    volumes:
    - netbox-redis-data:/data
    ports:
      - "6379:6379"
    env_file: docker/env/redis.env
  redis-cache:
    image: redis:6-alpine
    command:
    - sh
    - -c # this is to evaluate the $REDIS_PASSWORD from the env
    - redis-server --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    env_file: docker/env/redis-cache.env

volumes:
  netbox-media-files:
    driver: local
  netbox-postgres-data:
    driver: local
  netbox-redis-data:
    driver: local
