- name: Emulator C1 R1
  site: Local Emulator (EMUL8R.000)
  slug: r1-c1-emul8r-000
- name: Emulator C1 R2
  site: Local Emulator (EMUL8R.000)
  slug: r2-c1-emul8r-000
- name: Emulator C1 R3
  site: Local Emulator (EMUL8R.000)
  slug: r3-c1-emul8r-000
- name: Emulator C1 R4
  site: Local Emulator (EMUL8R.000)
  slug: r4-c1-emul8r-000
- name: Emulator C1 R5
  site: Local Emulator (EMUL8R.000)
  slug: r5-c1-emul8r-000
- name: Emulator C1 R6
  site: Local Emulator (EMUL8R.000)
  slug: r6-c1-emul8r-000
